### ISSUE TITLE
how to config webpack devServer' before(app)

### ISSUE THREAD

**Issue by ylyxf** [harrysolovay/rescripts#88]
I want to integration mocker-api in my create-react-app .
as the mocker-api document  say , as this code in `webpack.config.js`:
 <pre> devServer: {
   ...
   before(app){
     apiMocker(app, path.resolve('./mocker/index.js'), {
       proxy: {
         '/repos/*': 'https://api.github.com/',
         '/:owner/:repo/raw/:ref/*': 'http://127.0.0.1:2018'
       },
       changeHost: true,
     })
   }
 },</pre>
what should i do in my .rescriptsrc.js ?

this is my .rescriptsrc.js:
<pre>const { appendWebpackPlugin } = require('@rescripts/utilities')
const webpack = require('webpack');
module.exports = [
    {
        devServer:  []

    },
    ['use-babel-config', '.babelrc']
    , appendWebpackPlugin(
        new webpack.DefinePlugin({
            'process.env': {
                LOCALE: JSON.stringify('zh-CN'),
            },
        }),
    )
];</pre>

**Comment by harrysolovay** [comment]
Try doing something along the following lines:

```js
const { appendWebpackPlugin } = require('@rescripts/utilities')
const webpack = require('webpack');

module.exports = [
  {
    devServer: () => ({
      before(app) {
        apiMocker(app, path.resolve('./mocker/index.js'),
        {
          proxy: {
            '/repos/*': 'https://api.github.com/',
            '/:owner/:repo/raw/:ref/*': 'http://127.0.0.1:2018'
          },
          changeHost: true,
        }),
      },
    },
  },
  ['use-babel-config', '.babelrc'],
  appendWebpackPlugin(
    new webpack.DefinePlugin({
      'process.env': {
        LOCALE: JSON.stringify('zh-CN'),
      },
    }),
  )
];
```

Let me know how this goes 👍

**Comment by ylyxf** [comment]
Thank you !  I works!
But still have a little problem:
when i add just  an empty devServer ,the cra project can run ,  but has an exception on startup :
<pre>
module.exports = [
    {
        devServer: () => ({
            
        })
    },
    ['use-babel-config', '.babelrc']
    , appendWebpackPlugin(
        new webpack.DefinePlugin({
            'process.env': {
                LOCALE: JSON.stringify('zh-CN'),
            },
        }),
    )
];
</pre>

<pre>
× ｢wds｣: Exception on "GET /sockjs-node" in filter "welcome_screen":
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:257:14)
    at Socket.Writable.write (_stream_writable.js:306:5)
    at Socket.Writable.end (_stream_writable.js:617:10)
    at Socket.end (net.js:580:31)
    at App.exports.GenericApp.GenericApp.handle_error (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:152:15)
    at execute_request (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:36:28)
    at IncomingMessage.req.next_filter (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:105:18)
    at Listener.webjs_handler (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:107:13)
    at Listener.handler (D:\Projects\shinein\node_modules\sockjs\lib\sockjs.js:150:12)
    at Listener.handler (D:\Projects\shinein\node_modules\sockjs\lib\sockjs.js:6:59)
× ｢wds｣: Exception on "GET /sockjs-node" in filter "welcome_screen":
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:257:14)
    at Socket.Writable.write (_stream_writable.js:306:5)
    at Socket.Writable.end (_stream_writable.js:617:10)
    at Socket.end (net.js:580:31)
    at App.exports.GenericApp.GenericApp.handle_error (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:152:15)
    at execute_request (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:36:28)
    at IncomingMessage.req.next_filter (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:105:18)
    at Listener.webjs_handler (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:107:13)
    at Listener.handler (D:\Projects\shinein\node_modules\sockjs\lib\sockjs.js:150:12)
    at Listener.handler (D:\Projects\shinein\node_modules\sockjs\lib\sockjs.js:6:59)
× ｢wds｣: Exception on "GET /sockjs-node" in filter "welcome_screen":
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:257:14)
    at Socket.Writable.write (_stream_writable.js:306:5)
    at Socket.Writable.end (_stream_writable.js:617:10)
    at Socket.end (net.js:580:31)
    at App.exports.GenericApp.GenericApp.handle_error (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:152:15)
    at execute_request (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:36:28)
    at IncomingMessage.req.next_filter (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:105:18)
    at Listener.webjs_handler (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:107:13)
    at Listener.handler (D:\Projects\shinein\node_modules\sockjs\lib\sockjs.js:150:12)
    at Listener.handler (D:\Projects\shinein\node_modules\sockjs\lib\sockjs.js:6:59)
× ｢wds｣: Exception on "GET /sockjs-node" in filter "welcome_screen":
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:257:14)
    at Socket.Writable.write (_stream_writable.js:306:5)
    at Socket.Writable.end (_stream_writable.js:617:10)
    at Socket.end (net.js:580:31)
    at App.exports.GenericApp.GenericApp.handle_error (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:152:15)
    at execute_request (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:36:28)
    at IncomingMessage.req.next_filter (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:105:18)
    at Listener.webjs_handler (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:107:13)
    at Listener.handler (D:\Projects\shinein\node_modules\sockjs\lib\sockjs.js:150:12)
    at Listener.handler (D:\Projects\shinein\node_modules\sockjs\lib\sockjs.js:6:59)
× ｢wds｣: Exception on "GET /sockjs-node" in filter "welcome_screen":
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:257:14)
    at Socket.Writable.write (_stream_writable.js:306:5)
    at Socket.Writable.end (_stream_writable.js:617:10)
    at Socket.end (net.js:580:31)
    at App.exports.GenericApp.GenericApp.handle_error (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:152:15)
    at execute_request (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:36:28)
    at IncomingMessage.req.next_filter (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:105:18)
    at Listener.webjs_handler (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:107:13)
    at Listener.handler (D:\Projects\shinein\node_modules\sockjs\lib\sockjs.js:150:12)
    at Listener.handler (D:\Projects\shinein\node_modules\sockjs\lib\sockjs.js:6:59)
× ｢wds｣: Exception on "GET /sockjs-node" in filter "welcome_screen":
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:257:14)
    at Socket.Writable.write (_stream_writable.js:306:5)
    at Socket.Writable.end (_stream_writable.js:617:10)
    at Socket.end (net.js:580:31)
    at App.exports.GenericApp.GenericApp.handle_error (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:152:15)
    at execute_request (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:36:28)
    at IncomingMessage.req.next_filter (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:105:18)
    at Listener.webjs_handler (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:107:13)
    at Listener.handler (D:\Projects\shinein\node_modules\sockjs\lib\sockjs.js:150:12)
    at Listener.handler (D:\Projects\shinein\node_modules\sockjs\lib\sockjs.js:6:59)
× ｢wds｣: Exception on "GET /sockjs-node" in filter "welcome_screen":
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:257:14)
    at Socket.Writable.write (_stream_writable.js:306:5)
    at Socket.Writable.end (_stream_writable.js:617:10)
    at Socket.end (net.js:580:31)
    at App.exports.GenericApp.GenericApp.handle_error (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:152:15)
    at execute_request (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:36:28)
    at IncomingMessage.req.next_filter (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:105:18)
    at Listener.webjs_handler (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:107:13)
    at Listener.handler (D:\Projects\shinein\node_modules\sockjs\lib\sockjs.js:150:12)
    at Listener.handler (D:\Projects\shinein\node_modules\sockjs\lib\sockjs.js:6:59)
× ｢wds｣: Exception on "GET /sockjs-node" in filter "welcome_screen":
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:257:14)
    at Socket.Writable.write (_stream_writable.js:306:5)
    at Socket.Writable.end (_stream_writable.js:617:10)
    at Socket.end (net.js:580:31)
    at App.exports.GenericApp.GenericApp.handle_error (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:152:15)
    at execute_request (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:36:28)
    at IncomingMessage.req.next_filter (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:105:18)
    at Listener.webjs_handler (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:107:13)
    at Listener.handler (D:\Projects\shinein\node_modules\sockjs\lib\sockjs.js:150:12)
    at Listener.handler (D:\Projects\shinein\node_modules\sockjs\lib\sockjs.js:6:59)
× ｢wds｣: Exception on "GET /sockjs-node" in filter "welcome_screen":
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:257:14)
    at Socket.Writable.write (_stream_writable.js:306:5)
    at Socket.Writable.end (_stream_writable.js:617:10)
    at Socket.end (net.js:580:31)
    at App.exports.GenericApp.GenericApp.handle_error (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:152:15)
    at execute_request (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:36:28)
    at IncomingMessage.req.next_filter (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:105:18)
    at Listener.webjs_handler (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:107:13)
    at Listener.handler (D:\Projects\shinein\node_modules\sockjs\lib\sockjs.js:150:12)
    at Listener.handler (D:\Projects\shinein\node_modules\sockjs\lib\sockjs.js:6:59)
× ｢wds｣: Exception on "GET /sockjs-node" in filter "welcome_screen":
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:257:14)
    at Socket.Writable.write (_stream_writable.js:306:5)
    at Socket.Writable.end (_stream_writable.js:617:10)
    at Socket.end (net.js:580:31)
    at App.exports.GenericApp.GenericApp.handle_error (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:152:15)
    at execute_request (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:36:28)
    at IncomingMessage.req.next_filter (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:105:18)
    at Listener.webjs_handler (D:\Projects\shinein\node_modules\sockjs\lib\webjs.js:107:13)
    at Listener.handler (D:\Projects\shinein\node_modules\sockjs\lib\sockjs.js:150:12)
    at Listener.handler (D:\Projects\shinein\node_modules\sockjs\lib\sockjs.js:6:59)
</pre>

**Comment by harrysolovay** [comment]
You're overriding the preexisting dev server config with an empty object. That's not a valid CRA dev server config. Hence the error.

**Comment by ylyxf** [comment]
when the config like this , the error is still exist
<pre>
{
        devServer: () => ({
            before(app) {
                apiMocker(app, path.resolve('./mock/index.js'), {})
            }
        })
    }
</pre>
 this code may  also overrid the preexisting dev server config.

is there any method to get the `CRA dev server config` ，so i can customize it,  merge  my
apiMocker ?

**Comment by harrysolovay** [comment]
Did you follow [the WebPack Dev Server documentation](https://webpack.js.org/configuration/dev-server/)?

**Comment by ylyxf** [comment]
i found the answer in rescripts readme: 
CodeA:
<pre>
devServer: () => ({
            before(app) {
                apiMocker(app, path.resolve('./mock/index.js'), {})
            }
        })
</pre>

CodeB:
<pre>
devServer: config => {
             newConfig = doConfig(config);
             return config ;
        }
</pre>
CodeA means **override** all  devServer config, CodeB means **change** devServer config.

I should use CodeB .

this is my cofig ,and it works:

<pre>
     const { appendWebpackPlugin } = require('@rescripts/utilities')
const webpack = require('webpack');
const path = require('path');
const apiMocker = require('mocker-api');

module.exports = [
    {
        devServer: config => {
            defaultBefore = config.before;
            config.before = (app, server) => {
                defaultBefore(app, server);
                apiMocker(app, path.resolve('./mock/index.js'), {})
            }
            return config
        }
    },
    ['use-babel-config', '.babelrc']
    , appendWebpackPlugin(
        new webpack.DefinePlugin({
            'process.env': {
                LOCALE: JSON.stringify('zh-CN'),
            },
        }),
    )
];
</pre>

thank you ! @harrysolovay
